import type {
  GraphEdge,
  GraphLayer,
  GraphNode,
  RelationType,
  TailNodeGroup,
} from "./graphData";

const layerColors: Record<GraphLayer, { color: string; accent: string }> = {
  source: { color: "#3466ff", accent: "#88aaff" },
  fact: { color: "#22c55e", accent: "#7ee6a8" },
  mechanism: { color: "#f59e0b", accent: "#ffd277" },
  outcome: { color: "#ef4444", accent: "#ff9d9d" },
};

function makeNode(node: Omit<GraphNode, "color" | "accent">): GraphNode {
  return {
    ...node,
    color: layerColors[node.layer].color,
    accent: layerColors[node.layer].accent,
  };
}

function makeEdge(
  id: string,
  source: string,
  target: string,
  relationType: RelationType,
  weight: number,
  confidence: number,
  summary: string,
): GraphEdge {
  return {
    id,
    source,
    target,
    relationType,
    weight,
    confidence,
    summary,
  };
}

export const baseNodes: GraphNode[] = [
  makeNode({
    id: "source_brand_website_product_page",
    label: "Brand Website Product Page",
    layer: "source",
    filterType: "source",
    entityType: "website_link",
    summary:
      "Official HeadEase PDP framing the serum around scalp comfort, dermatologist validation, and a clean daily routine.",
    x: 150,
    y: 120,
    size: 24,
    weight: 0.96,
    opacity: 1,
    showLabel: true,
    sourceDetails: {
      title: "HeadEase Scalp Repair Serum Product Page",
      sourceType: "Brand Website",
      shortSummary:
        "Official page positions the serum as a fast-comfort, non-greasy scalp treatment for daily use.",
      reliability: 0.94,
      excerpt:
        "Dermatologist-tested scalp serum that helps calm visible discomfort in 7 days with a lightweight, non-greasy finish.",
    },
  }),
  makeNode({
    id: "source_tiktok_comment_summary",
    label: "TikTok Comment Summary",
    layer: "source",
    filterType: "source",
    entityType: "comment_summary",
    summary:
      "Aggregated TikTok reactions showing relief-seeking behavior, irritation anxiety, and repeated trust questions before purchase.",
    x: 140,
    y: 240,
    size: 22,
    weight: 0.91,
    opacity: 0.96,
    showLabel: true,
    sourceDetails: {
      title: "HeadEase TikTok Comments Weekly Synthesis",
      sourceType: "Comment Summary",
      shortSummary:
        "High-volume comment synthesis from creator seeding and competitor comparison posts.",
      reliability: 0.82,
      excerpt:
        "Users repeatedly ask whether it helps itch fast, whether it can irritate sensitive scalps, and whether the dermatologist claim is real.",
    },
  }),
  makeNode({
    id: "source_instagram_content_summary",
    label: "Instagram Content Summary",
    layer: "source",
    filterType: "source",
    entityType: "content_digest",
    summary:
      "Instagram content digest showing stronger saves and shares on polished routines, ingredient explainers, and clean aesthetic storytelling.",
    x: 155,
    y: 360,
    size: 21,
    weight: 0.86,
    opacity: 0.92,
    showLabel: true,
    sourceDetails: {
      title: "Instagram Organic Content Summary",
      sourceType: "Content Summary",
      shortSummary:
        "Digest of recent brand and creator posts, highlighting what creative formats sustain attention on Instagram.",
      reliability: 0.78,
      excerpt:
        "Ingredient breakdowns and polished routine demos drive more saves, while overtly dramatic claims generate lower trust in comments.",
    },
  }),
  makeNode({
    id: "source_user_interview_notes",
    label: "User Interview Notes",
    layer: "source",
    filterType: "source",
    entityType: "interview_summary",
    summary:
      "Interview notes from US scalp-care shoppers focused on ingredient safety, proof, and price-value justification.",
    x: 150,
    y: 500,
    size: 23,
    weight: 0.9,
    opacity: 0.95,
    showLabel: true,
    sourceDetails: {
      title: "US Scalp Care Interview Notes",
      sourceType: "User Interview Summary",
      shortSummary:
        "1:1 interview synthesis across first-time scalp-serum buyers and category switchers.",
      reliability: 0.88,
      excerpt:
        "Ingredient-conscious buyers want efficacy proof before trying a new serum, and price-sensitive shoppers need a clear reason to trade up.",
    },
  }),
  makeNode({
    id: "source_competitor_analysis_summary",
    label: "Competitor Analysis Summary",
    layer: "source",
    filterType: "source",
    entityType: "competitor_scrape",
    summary:
      "Competitive scan comparing HeadEase against NutraRoot and ClearScalp Lab across claim language, visual framing, and price posture.",
    x: 150,
    y: 620,
    size: 22,
    weight: 0.89,
    opacity: 0.94,
    showLabel: true,
    sourceDetails: {
      title: "Competitive Positioning Summary",
      sourceType: "Competitor Analysis",
      shortSummary:
        "Cross-platform audit of competitor pages, creator hooks, and conversion tactics.",
      reliability: 0.85,
      excerpt:
        "NutraRoot owns herbal calm and community proof, while ClearScalp Lab signals clinical precision and premium efficacy.",
    },
  }),
  makeNode({
    id: "source_insight_report_fragment",
    label: "Insight Report Fragment",
    layer: "source",
    filterType: "source",
    entityType: "insight_report",
    summary:
      "Research fragment on US scalp wellness behavior, content fatigue, and short-form platform expectations.",
    x: 150,
    y: 740,
    size: 21,
    weight: 0.84,
    opacity: 0.9,
    showLabel: true,
    sourceDetails: {
      title: "US Scalp Wellness Insight Report Fragment",
      sourceType: "Insight Report",
      shortSummary:
        "Internal strategy report describing category growth, creator dynamics, and friction points.",
      reliability: 0.8,
      excerpt:
        "Younger scalp-care audiences respond to emotionally relevant openings, but repetitive claim stacking lowers completion and trust.",
    },
  }),
  makeNode({
    id: "source_memory_bank_brand_history",
    label: "Historical Brand Positioning Memory",
    layer: "source",
    filterType: "source",
    entityType: "memory_entry",
    summary:
      "Memory-bank entry summarizing how HeadEase has historically won with clean, reassuring, low-irritation positioning.",
    x: 150,
    y: 860,
    size: 20,
    weight: 0.83,
    opacity: 0.88,
    showLabel: true,
    sourceDetails: {
      title: "Memory Bank: Historical Brand Selling Points",
      sourceType: "Memory Entry",
      shortSummary:
        "Archived synthesis of prior winning claims, visuals, and audience responses from adjacent launches.",
      reliability: 0.76,
      excerpt:
        "HeadEase tends to overperform when clean ingredients and comfort language appear before hard efficacy claims.",
    },
  }),
  makeNode({
    id: "brand_headease",
    label: "HeadEase",
    layer: "fact",
    filterType: "brand",
    entityType: "brand",
    summary:
      "HeadEase is the focal brand, positioned around scalp comfort, ingredient reassurance, and a modern clean-care feel.",
    x: 500,
    y: 215,
    size: 28,
    weight: 0.98,
    opacity: 1,
    showLabel: true,
    factDetails: {
      category: "Brand",
      relatedBrands: ["HeadEase", "NutraRoot", "ClearScalp Lab"],
      relatedPlatforms: ["TikTok", "Instagram"],
      relatedUsers: ["Ingredient-Conscious Buyers", "Sensitive Scalp Users"],
    },
  }),
  makeNode({
    id: "product_scalp_repair_serum",
    label: "Scalp Repair Serum",
    layer: "fact",
    filterType: "product",
    entityType: "product",
    summary:
      "The hero serum is framed as a lightweight scalp-repair treatment that must balance proof, comfort, and trust.",
    x: 655,
    y: 235,
    size: 30,
    weight: 1,
    opacity: 1,
    showLabel: true,
    factDetails: {
      category: "Product",
      relatedBrands: ["HeadEase"],
      relatedPlatforms: ["TikTok", "Instagram"],
      relatedUsers: ["Young Women 18-24", "Working Women 25-34"],
    },
  }),
  makeNode({
    id: "category_scalp_care",
    label: "Scalp Care Category",
    layer: "fact",
    filterType: "product",
    entityType: "category",
    summary:
      "Category anchor representing US scalp-care serums where comfort, oil balance, and safety reassurance shape demand.",
    x: 510,
    y: 90,
    size: 20,
    weight: 0.82,
    opacity: 0.9,
    showLabel: true,
    factDetails: {
      category: "Category",
      relatedBrands: ["HeadEase", "NutraRoot", "ClearScalp Lab"],
    },
  }),
  makeNode({
    id: "brand_nutraroot",
    label: "NutraRoot",
    layer: "fact",
    filterType: "brand",
    entityType: "competitor_brand",
    summary:
      "Competitor A leaning into herbal calm, everyday creator proof, and softer community language.",
    x: 485,
    y: 390,
    size: 20,
    weight: 0.76,
    opacity: 0.88,
    factDetails: {
      category: "Competitor Brand",
      relatedBrands: ["HeadEase", "NutraRoot"],
    },
  }),
  makeNode({
    id: "brand_clearscalp_lab",
    label: "ClearScalp Lab",
    layer: "fact",
    filterType: "brand",
    entityType: "competitor_brand",
    summary:
      "Competitor B using premium clinical framing, lab visuals, and stronger efficacy cues.",
    x: 485,
    y: 515,
    size: 20,
    weight: 0.77,
    opacity: 0.88,
    factDetails: {
      category: "Competitor Brand",
      relatedBrands: ["HeadEase", "ClearScalp Lab"],
    },
  }),
  makeNode({
    id: "historical_brand_positioning",
    label: "Historical Brand Positioning",
    layer: "fact",
    filterType: "brand",
    entityType: "brand_memory",
    summary:
      "Historic win pattern where calm, clean, and gentle efficacy cues outperform aggressive transformation claims.",
    x: 705,
    y: 95,
    size: 17,
    weight: 0.72,
    opacity: 0.82,
    factDetails: {
      category: "Brand Memory",
      relatedBrands: ["HeadEase"],
    },
  }),
  makeNode({
    id: "competitor_nutraroot_herbal_halo",
    label: "NutraRoot Herbal Halo",
    layer: "fact",
    filterType: "brand",
    entityType: "competitor_feature",
    summary:
      "NutraRoot's repeated use of botanical calm cues creates an approachable, natural-trust halo.",
    x: 705,
    y: 400,
    size: 15,
    weight: 0.63,
    opacity: 0.8,
    factDetails: {
      category: "Competitor Feature",
      relatedBrands: ["NutraRoot"],
    },
  }),
  makeNode({
    id: "competitor_clearscalp_clinical_aesthetic",
    label: "ClearScalp Clinical Aesthetic",
    layer: "fact",
    filterType: "brand",
    entityType: "competitor_feature",
    summary:
      "ClearScalp Lab's clinical visual system signals high efficacy but also raises expectations and price assumptions.",
    x: 710,
    y: 525,
    size: 15,
    weight: 0.64,
    opacity: 0.8,
    factDetails: {
      category: "Competitor Feature",
      relatedBrands: ["ClearScalp Lab"],
    },
  }),
  makeNode({
    id: "user_young_women_18_24",
    label: "Young Women 18-24",
    layer: "fact",
    filterType: "user",
    entityType: "target_user",
    summary:
      "This cohort responds quickly to emotional hooks and social proof but punishes overly salesy language.",
    x: 470,
    y: 705,
    size: 20,
    weight: 0.83,
    opacity: 0.9,
    showLabel: true,
    factDetails: {
      category: "Audience Segment",
      relatedUsers: ["Young Women 18-24"],
      relatedPlatforms: ["TikTok", "Instagram"],
    },
  }),
  makeNode({
    id: "user_working_women_25_34",
    label: "Working Women 25-34",
    layer: "fact",
    filterType: "user",
    entityType: "target_user",
    summary:
      "Older segment values credibility, daily-routine ease, and strong price-value explanation before converting.",
    x: 555,
    y: 805,
    size: 19,
    weight: 0.81,
    opacity: 0.88,
    factDetails: {
      category: "Audience Segment",
      relatedUsers: ["Working Women 25-34"],
      relatedPlatforms: ["Instagram"],
    },
  }),
  makeNode({
    id: "user_sensitive_scalp_users",
    label: "Sensitive Scalp Users",
    layer: "fact",
    filterType: "user",
    entityType: "target_user",
    summary:
      "High-anxiety users focused on irritation avoidance, dermatologist backing, and ingredient reassurance.",
    x: 390,
    y: 610,
    size: 19,
    weight: 0.78,
    opacity: 0.87,
    factDetails: {
      category: "Audience Segment",
      relatedUsers: ["Sensitive Scalp Users"],
    },
  }),
  makeNode({
    id: "user_ingredient_conscious_buyers",
    label: "Ingredient-Conscious Buyers",
    layer: "fact",
    filterType: "user",
    entityType: "target_user",
    summary:
      "Ingredient-literate buyers who want a clean story plus enough proof to justify a trial.",
    x: 625,
    y: 690,
    size: 19,
    weight: 0.8,
    opacity: 0.88,
    factDetails: {
      category: "Audience Segment",
      relatedUsers: ["Ingredient-Conscious Buyers"],
      relatedPlatforms: ["Instagram"],
    },
  }),
  makeNode({
    id: "user_price_sensitive_buyers",
    label: "Price-Sensitive Buyers",
    layer: "fact",
    filterType: "user",
    entityType: "target_user",
    summary:
      "Price-sensitive shoppers need visible rationale for premium pricing or faster proof of value.",
    x: 705,
    y: 820,
    size: 18,
    weight: 0.74,
    opacity: 0.84,
    factDetails: {
      category: "Audience Segment",
      relatedUsers: ["Price-Sensitive Buyers"],
    },
  }),
  makeNode({
    id: "platform_tiktok",
    label: "TikTok",
    layer: "fact",
    filterType: "platform",
    entityType: "platform",
    summary:
      "TikTok rewards emotional openings, creator-native framing, and quick proof loops.",
    x: 890,
    y: 225,
    size: 20,
    weight: 0.87,
    opacity: 0.91,
    showLabel: true,
    factDetails: {
      category: "Platform",
      relatedPlatforms: ["TikTok"],
      relatedUsers: ["Young Women 18-24"],
    },
  }),
  makeNode({
    id: "platform_instagram",
    label: "Instagram",
    layer: "fact",
    filterType: "platform",
    entityType: "platform",
    summary:
      "Instagram favors polish, ingredient explainers, and routines that feel saveable and trustworthy.",
    x: 890,
    y: 370,
    size: 20,
    weight: 0.85,
    opacity: 0.9,
    showLabel: true,
    factDetails: {
      category: "Platform",
      relatedPlatforms: ["Instagram"],
      relatedUsers: ["Working Women 25-34", "Ingredient-Conscious Buyers"],
    },
  }),
  makeNode({
    id: "selling_soothing_scalp_irritation",
    label: "Soothing scalp irritation",
    layer: "fact",
    filterType: "selling_point",
    entityType: "selling_point",
    summary:
      "HeadEase's most emotionally resonant promise because it maps directly to itch and irritation pain.",
    x: 760,
    y: 125,
    size: 18,
    weight: 0.84,
    opacity: 0.92,
    factDetails: {
      category: "Selling Point",
      relatedBrands: ["HeadEase"],
      relatedUsers: ["Sensitive Scalp Users", "Young Women 18-24"],
    },
  }),
  makeNode({
    id: "selling_lightweight_non_greasy_texture",
    label: "Lightweight non-greasy texture",
    layer: "fact",
    filterType: "selling_point",
    entityType: "selling_point",
    summary:
      "Useful functional proof point for daily wear and for users worried about heavy scalp residue.",
    x: 760,
    y: 180,
    size: 17,
    weight: 0.79,
    opacity: 0.88,
    factDetails: {
      category: "Selling Point",
      relatedBrands: ["HeadEase"],
      relatedUsers: ["Working Women 25-34"],
    },
  }),
  makeNode({
    id: "selling_visible_scalp_comfort_7_days",
    label: "Visible scalp comfort in 7 days",
    layer: "fact",
    filterType: "selling_point",
    entityType: "selling_point",
    summary:
      "Compressed efficacy window that improves clarity but can backfire if the claim feels overstated.",
    x: 760,
    y: 235,
    size: 18,
    weight: 0.86,
    opacity: 0.9,
    factDetails: {
      category: "Selling Point",
      relatedBrands: ["HeadEase"],
      relatedUsers: ["Price-Sensitive Buyers", "Ingredient-Conscious Buyers"],
    },
  }),
  makeNode({
    id: "selling_dermatologist_tested",
    label: "Dermatologist-tested",
    layer: "fact",
    filterType: "selling_point",
    entityType: "selling_point",
    summary:
      "Trust-supporting proof cue that lowers safety anxiety for sensitive-scalp audiences.",
    x: 760,
    y: 290,
    size: 18,
    weight: 0.88,
    opacity: 0.92,
    factDetails: {
      category: "Selling Point",
      relatedBrands: ["HeadEase"],
      relatedUsers: ["Sensitive Scalp Users", "Ingredient-Conscious Buyers"],
    },
  }),
  makeNode({
    id: "selling_clean_ingredient_story",
    label: "Clean ingredient story",
    layer: "fact",
    filterType: "selling_point",
    entityType: "selling_point",
    summary:
      "Important emotional and identity cue, especially for users already scanning ingredient lists.",
    x: 760,
    y: 345,
    size: 18,
    weight: 0.84,
    opacity: 0.9,
    factDetails: {
      category: "Selling Point",
      relatedBrands: ["HeadEase"],
      relatedUsers: ["Ingredient-Conscious Buyers"],
    },
  }),
  makeNode({
    id: "content_before_after_story",
    label: "before_after_story",
    layer: "fact",
    filterType: "platform",
    entityType: "content_form",
    summary:
      "A direct proof-oriented format that performs best when creator-native rather than overproduced.",
    x: 975,
    y: 120,
    size: 16,
    weight: 0.77,
    opacity: 0.84,
    factDetails: {
      category: "Content Form",
      relatedPlatforms: ["TikTok"],
      relatedUsers: ["Young Women 18-24"],
    },
  }),
  makeNode({
    id: "content_expert_explanation",
    label: "expert_explanation",
    layer: "fact",
    filterType: "platform",
    entityType: "content_form",
    summary:
      "A credibility format where ingredients and mechanism are explained with authority cues.",
    x: 980,
    y: 180,
    size: 16,
    weight: 0.74,
    opacity: 0.82,
    factDetails: {
      category: "Content Form",
      relatedPlatforms: ["Instagram"],
      relatedUsers: ["Ingredient-Conscious Buyers"],
    },
  }),
  makeNode({
    id: "content_quick_routine_demo",
    label: "quick_routine_demo",
    layer: "fact",
    filterType: "platform",
    entityType: "content_form",
    summary:
      "Fast routine format that shows easy usage and lowers perceived effort on both target platforms.",
    x: 975,
    y: 240,
    size: 16,
    weight: 0.76,
    opacity: 0.83,
    factDetails: {
      category: "Content Form",
      relatedPlatforms: ["TikTok", "Instagram"],
    },
  }),
  makeNode({
    id: "content_ingredient_breakdown",
    label: "ingredient_breakdown",
    layer: "fact",
    filterType: "platform",
    entityType: "content_form",
    summary:
      "High-trust explainer format that can help conversion, but too much detail increases cognitive effort.",
    x: 980,
    y: 300,
    size: 16,
    weight: 0.79,
    opacity: 0.85,
    factDetails: {
      category: "Content Form",
      relatedPlatforms: ["Instagram"],
      relatedUsers: ["Ingredient-Conscious Buyers"],
    },
  }),
  makeNode({
    id: "content_emotional_problem_hook",
    label: "emotional_problem_hook",
    layer: "fact",
    filterType: "platform",
    entityType: "content_form",
    summary:
      "Emotion-led opening that dramatizes scalp discomfort to earn the first seconds of attention.",
    x: 980,
    y: 360,
    size: 16,
    weight: 0.82,
    opacity: 0.86,
    factDetails: {
      category: "Content Form",
      relatedPlatforms: ["TikTok"],
      relatedUsers: ["Young Women 18-24"],
    },
  }),
  makeNode({
    id: "concern_itch_relief",
    label: "itch relief",
    layer: "fact",
    filterType: "user",
    entityType: "user_concern",
    summary:
      "A primary symptom-level concern appearing consistently in comments and interviews.",
    x: 635,
    y: 560,
    size: 16,
    weight: 0.8,
    opacity: 0.86,
    factDetails: {
      category: "User Concern",
      relatedUsers: ["Sensitive Scalp Users", "Young Women 18-24"],
    },
  }),
  makeNode({
    id: "concern_oil_control",
    label: "oil control",
    layer: "fact",
    filterType: "user",
    entityType: "user_concern",
    summary:
      "Secondary concern tied to daily routine compatibility and fear of scalp buildup.",
    x: 730,
    y: 610,
    size: 15,
    weight: 0.66,
    opacity: 0.78,
    factDetails: {
      category: "User Concern",
      relatedUsers: ["Working Women 25-34"],
    },
  }),
  makeNode({
    id: "concern_trustworthiness",
    label: "trustworthiness",
    layer: "fact",
    filterType: "user",
    entityType: "user_concern",
    summary:
      "Trustworthiness is a gating concern before users accept efficacy or safety claims.",
    x: 635,
    y: 625,
    size: 17,
    weight: 0.85,
    opacity: 0.88,
    factDetails: {
      category: "User Concern",
      relatedUsers: ["Ingredient-Conscious Buyers", "Sensitive Scalp Users"],
    },
  }),
  makeNode({
    id: "concern_proof_of_efficacy",
    label: "proof of efficacy",
    layer: "fact",
    filterType: "user",
    entityType: "user_concern",
    summary:
      "Users want a believable proof loop connecting timeframe, mechanism, and expected result.",
    x: 760,
    y: 690,
    size: 17,
    weight: 0.86,
    opacity: 0.88,
    factDetails: {
      category: "User Concern",
      relatedUsers: ["Ingredient-Conscious Buyers", "Price-Sensitive Buyers"],
    },
  }),
  makeNode({
    id: "concern_fear_of_irritation",
    label: "fear of irritation",
    layer: "fact",
    filterType: "user",
    entityType: "user_concern",
    summary:
      "A major risk lens for sensitive users who need evidence that the serum will not make things worse.",
    x: 515,
    y: 595,
    size: 17,
    weight: 0.84,
    opacity: 0.87,
    factDetails: {
      category: "User Concern",
      relatedUsers: ["Sensitive Scalp Users"],
    },
  }),
  makeNode({
    id: "concern_price_value_balance",
    label: "price-value balance",
    layer: "fact",
    filterType: "user",
    entityType: "user_concern",
    summary:
      "The value question decides whether proof becomes purchase interest or stalls at consideration.",
    x: 820,
    y: 785,
    size: 16,
    weight: 0.75,
    opacity: 0.82,
    factDetails: {
      category: "User Concern",
      relatedUsers: ["Price-Sensitive Buyers", "Working Women 25-34"],
    },
  }),
  makeNode({
    id: "risk_exaggerated_claims",
    label: "exaggerated claims",
    layer: "fact",
    filterType: "risk",
    entityType: "risk_claim",
    summary:
      "Overstated transformation language makes the 7-day claim feel less believable and triggers skepticism.",
    x: 965,
    y: 520,
    size: 17,
    weight: 0.79,
    opacity: 0.84,
    factDetails: {
      category: "Risk Claim",
      relatedBrands: ["HeadEase"],
    },
  }),
  makeNode({
    id: "risk_too_many_claims",
    label: "too_many_claims",
    layer: "fact",
    filterType: "risk",
    entityType: "risk_claim",
    summary:
      "When too many benefits are stacked, audiences struggle to retain the core message.",
    x: 965,
    y: 590,
    size: 17,
    weight: 0.77,
    opacity: 0.82,
    factDetails: {
      category: "Risk Claim",
      relatedBrands: ["HeadEase"],
    },
  }),
  makeNode({
    id: "risk_high_price_positioning",
    label: "high_price_positioning",
    layer: "fact",
    filterType: "risk",
    entityType: "risk_claim",
    summary:
      "Premium positioning without enough proof or routine clarity creates conversion drag.",
    x: 965,
    y: 660,
    size: 17,
    weight: 0.78,
    opacity: 0.84,
    factDetails: {
      category: "Risk Claim",
      relatedBrands: ["HeadEase"],
    },
  }),
  makeNode({
    id: "mechanism_hook_strength",
    label: "Hook Strength",
    layer: "mechanism",
    filterType: "mechanism",
    entityType: "mechanism",
    summary:
      "Measures whether the opening earns the first click and the first seconds of attention.",
    x: 1185,
    y: 120,
    size: 18,
    weight: 0.9,
    opacity: 0.95,
    showLabel: true,
    mechanismDetails: {
      impactDirection: "Higher hook strength raises initial click probability.",
    },
  }),
  makeNode({
    id: "mechanism_benefit_clarity",
    label: "Benefit Clarity",
    layer: "mechanism",
    filterType: "mechanism",
    entityType: "mechanism",
    summary:
      "Tracks how easily users understand what the serum does and how fast the benefit lands.",
    x: 1185,
    y: 205,
    size: 18,
    weight: 0.89,
    opacity: 0.94,
    showLabel: true,
    mechanismDetails: {
      impactDirection: "Higher clarity improves comprehension and retention.",
    },
  }),
  makeNode({
    id: "mechanism_trust_formation",
    label: "Trust Formation",
    layer: "mechanism",
    filterType: "mechanism",
    entityType: "mechanism",
    summary:
      "Captures whether the audience believes the product is safe, credible, and worth trying.",
    x: 1185,
    y: 290,
    size: 19,
    weight: 0.93,
    opacity: 0.97,
    showLabel: true,
    mechanismDetails: {
      impactDirection: "Higher trust lifts conversion readiness and lowers safety hesitation.",
    },
  }),
  makeNode({
    id: "mechanism_native_platform_fit",
    label: "Native Platform Fit",
    layer: "mechanism",
    filterType: "mechanism",
    entityType: "mechanism",
    summary:
      "Represents how natural the creative feels inside TikTok or Instagram consumption habits.",
    x: 1185,
    y: 375,
    size: 18,
    weight: 0.86,
    opacity: 0.92,
    showLabel: true,
    mechanismDetails: {
      impactDirection: "Higher native fit improves sharing and lowers resistance to the ad message.",
    },
  }),
  makeNode({
    id: "mechanism_cognitive_load",
    label: "Cognitive Load",
    layer: "mechanism",
    filterType: "mechanism",
    entityType: "mechanism",
    summary:
      "Represents the mental effort required to parse the message, claims, and ingredients.",
    x: 1185,
    y: 460,
    size: 18,
    weight: 0.83,
    opacity: 0.9,
    showLabel: true,
    mechanismDetails: {
      impactDirection: "Higher cognitive load hurts watch retention and clarity.",
    },
  }),
  makeNode({
    id: "mechanism_social_proof",
    label: "Social Proof",
    layer: "mechanism",
    filterType: "mechanism",
    entityType: "mechanism",
    summary:
      "Measures whether the audience sees believable evidence that people like them are getting results.",
    x: 1185,
    y: 545,
    size: 18,
    weight: 0.84,
    opacity: 0.9,
    showLabel: true,
    mechanismDetails: {
      impactDirection: "Higher social proof boosts comments, saves, and perceived legitimacy.",
    },
  }),
  makeNode({
    id: "mechanism_conversion_friction",
    label: "Conversion Friction",
    layer: "mechanism",
    filterType: "mechanism",
    entityType: "mechanism",
    summary:
      "Captures price, effort, and uncertainty barriers that slow the move from interest to purchase.",
    x: 1185,
    y: 630,
    size: 18,
    weight: 0.82,
    opacity: 0.89,
    showLabel: true,
    mechanismDetails: {
      impactDirection: "Higher friction lowers purchase intent even when sentiment is positive.",
    },
  }),
  makeNode({
    id: "mechanism_emotional_resonance",
    label: "Emotional Resonance",
    layer: "mechanism",
    filterType: "mechanism",
    entityType: "mechanism",
    summary:
      "Represents whether the message feels personally relevant to the user's scalp problem and identity.",
    x: 1185,
    y: 715,
    size: 18,
    weight: 0.87,
    opacity: 0.93,
    showLabel: true,
    mechanismDetails: {
      impactDirection: "Higher resonance lifts positive sentiment and shareability.",
    },
  }),
  makeNode({
    id: "mechanism_skepticism_trigger",
    label: "Skepticism Trigger",
    layer: "mechanism",
    filterType: "mechanism",
    entityType: "mechanism",
    summary:
      "Captures the moment a claim feels too polished, too strong, or too unbelievable to trust.",
    x: 1185,
    y: 800,
    size: 18,
    weight: 0.86,
    opacity: 0.92,
    showLabel: true,
    mechanismDetails: {
      impactDirection: "Higher skepticism lowers positive sentiment and raises perceived risk.",
    },
  }),
  makeNode({
    id: "mechanism_content_fatigue",
    label: "Content Fatigue",
    layer: "mechanism",
    filterType: "mechanism",
    entityType: "mechanism",
    summary:
      "Represents how repeated claim tropes make the audience tune out even before proof lands.",
    x: 1185,
    y: 885,
    size: 17,
    weight: 0.72,
    opacity: 0.82,
    mechanismDetails: {
      impactDirection: "Higher fatigue weakens retention and comment energy.",
    },
  }),
  makeNode({
    id: "outcome_click_intent",
    label: "Click Intent",
    layer: "outcome",
    filterType: "result",
    entityType: "outcome",
    summary:
      "Probability that the audience clicks through after seeing the creative or ad unit.",
    x: 1475,
    y: 160,
    size: 20,
    weight: 0.91,
    opacity: 0.97,
    showLabel: true,
    outcomeDetails: {
      currentTendency: "Medium-High",
      riskHint: "Falls quickly if emotional hooks feel generic or too ad-like.",
    },
  }),
  makeNode({
    id: "outcome_watch_retention",
    label: "Watch Retention",
    layer: "outcome",
    filterType: "result",
    entityType: "outcome",
    summary:
      "Likelihood that users stay long enough to absorb the benefit story and proof sequence.",
    x: 1475,
    y: 280,
    size: 20,
    weight: 0.89,
    opacity: 0.95,
    showLabel: true,
    outcomeDetails: {
      currentTendency: "Medium",
      riskHint: "Sensitive to claim stacking, complexity, and repetitive creator structures.",
    },
  }),
  makeNode({
    id: "outcome_positive_sentiment",
    label: "Positive Sentiment",
    layer: "outcome",
    filterType: "result",
    entityType: "outcome",
    summary:
      "Overall positivity in reactions, shaped by resonance, trust, and skepticism control.",
    x: 1475,
    y: 400,
    size: 20,
    weight: 0.9,
    opacity: 0.96,
    showLabel: true,
    outcomeDetails: {
      currentTendency: "Medium-High",
      riskHint: "Drops when efficacy language outruns available proof or safety cues.",
    },
  }),
  makeNode({
    id: "outcome_comment_engagement",
    label: "Comment Engagement",
    layer: "outcome",
    filterType: "result",
    entityType: "outcome",
    summary:
      "Volume and quality of questions, tags, and reactions generated by the content.",
    x: 1475,
    y: 520,
    size: 20,
    weight: 0.84,
    opacity: 0.92,
    showLabel: true,
    outcomeDetails: {
      currentTendency: "Medium-High",
      riskHint: "Can skew negative if social proof is weak and comments become challenge-driven.",
    },
  }),
  makeNode({
    id: "outcome_share_potential",
    label: "Share Potential",
    layer: "outcome",
    filterType: "result",
    entityType: "outcome",
    summary:
      "Likelihood that the content gets sent, saved, or reposted within the target audience.",
    x: 1475,
    y: 640,
    size: 20,
    weight: 0.8,
    opacity: 0.9,
    showLabel: true,
    outcomeDetails: {
      currentTendency: "Medium",
      riskHint: "Needs platform-native packaging more than technical proof alone.",
    },
  }),
  makeNode({
    id: "outcome_conversion_interest",
    label: "Conversion Interest",
    layer: "outcome",
    filterType: "result",
    entityType: "outcome",
    summary:
      "Predicted readiness to add to cart, search further, or enter a purchase evaluation flow.",
    x: 1475,
    y: 760,
    size: 21,
    weight: 0.92,
    opacity: 0.97,
    showLabel: true,
    outcomeDetails: {
      currentTendency: "Medium-High",
      riskHint: "Most vulnerable to price friction and weak trust formation.",
    },
  }),
  makeNode({
    id: "outcome_risk_exposure",
    label: "Risk Exposure",
    layer: "outcome",
    filterType: "result",
    entityType: "outcome",
    summary:
      "Probability that the campaign invites backlash, disbelief, or brand-damaging commentary.",
    x: 1475,
    y: 880,
    size: 19,
    weight: 0.78,
    opacity: 0.9,
    showLabel: true,
    outcomeDetails: {
      currentTendency: "Medium",
      riskHint: "Rises when bold efficacy claims outrun source strength and comment moderation.",
    },
  }),
];

export const baseEdges: GraphEdge[] = [
  makeEdge(
    "edge_source_tiktok_mentions_itch",
    "source_tiktok_comment_summary",
    "concern_itch_relief",
    "mentions",
    0.84,
    0.8,
    "TikTok comments repeatedly mention itch relief as the first proof question.",
  ),
  makeEdge(
    "edge_source_tiktok_mentions_fear",
    "source_tiktok_comment_summary",
    "concern_fear_of_irritation",
    "mentions",
    0.83,
    0.79,
    "TikTok comments surface fear of irritation as a recurring blocker.",
  ),
  makeEdge(
    "edge_source_tiktok_mentions_trust",
    "source_tiktok_comment_summary",
    "concern_trustworthiness",
    "mentions",
    0.8,
    0.78,
    "TikTok comments question whether the product can be trusted.",
  ),
  makeEdge(
    "edge_source_interviews_mentions_ingredient_buyers",
    "source_user_interview_notes",
    "user_ingredient_conscious_buyers",
    "mentions",
    0.86,
    0.87,
    "Interviews identify ingredient-conscious buyers as a key decision maker group.",
  ),
  makeEdge(
    "edge_source_interviews_mentions_proof",
    "source_user_interview_notes",
    "concern_proof_of_efficacy",
    "mentions",
    0.88,
    0.88,
    "Interviewed shoppers ask for credible efficacy proof before trial.",
  ),
  makeEdge(
    "edge_source_interviews_mentions_price",
    "source_user_interview_notes",
    "concern_price_value_balance",
    "mentions",
    0.83,
    0.86,
    "Interviews show that price-value balance determines willingness to switch.",
  ),
  makeEdge(
    "edge_source_brand_supports_derm",
    "source_brand_website_product_page",
    "selling_dermatologist_tested",
    "supports",
    0.93,
    0.94,
    "The official product page supports the dermatologist-tested claim.",
  ),
  makeEdge(
    "edge_source_brand_supports_texture",
    "source_brand_website_product_page",
    "selling_lightweight_non_greasy_texture",
    "supports",
    0.91,
    0.93,
    "The product page emphasizes a lightweight non-greasy finish.",
  ),
  makeEdge(
    "edge_source_brand_supports_7days",
    "source_brand_website_product_page",
    "selling_visible_scalp_comfort_7_days",
    "supports",
    0.92,
    0.92,
    "The product page repeats the 7-day comfort timeline.",
  ),
  makeEdge(
    "edge_source_brand_supports_product",
    "source_brand_website_product_page",
    "product_scalp_repair_serum",
    "contains",
    0.95,
    0.95,
    "The brand website is the primary source page for the serum.",
  ),
  makeEdge(
    "edge_source_competitor_compares_nutra",
    "source_competitor_analysis_summary",
    "brand_nutraroot",
    "compares_with",
    0.88,
    0.84,
    "Competitive analysis directly compares HeadEase with NutraRoot.",
  ),
  makeEdge(
    "edge_source_competitor_compares_clear",
    "source_competitor_analysis_summary",
    "brand_clearscalp_lab",
    "compares_with",
    0.89,
    0.84,
    "Competitive analysis directly compares HeadEase with ClearScalp Lab.",
  ),
  makeEdge(
    "edge_source_memory_supports_clean",
    "source_memory_bank_brand_history",
    "selling_clean_ingredient_story",
    "supports",
    0.82,
    0.76,
    "Memory bank supports clean ingredient storytelling as a historic win.",
  ),
  makeEdge(
    "edge_source_memory_supports_history",
    "source_memory_bank_brand_history",
    "historical_brand_positioning",
    "supports",
    0.85,
    0.78,
    "Memory bank preserves HeadEase's historical positioning logic.",
  ),
  makeEdge(
    "edge_source_instagram_mentions_breakdown",
    "source_instagram_content_summary",
    "content_ingredient_breakdown",
    "mentions",
    0.82,
    0.76,
    "Instagram digest mentions ingredient breakdowns as a strong format.",
  ),
  makeEdge(
    "edge_source_instagram_mentions_demo",
    "source_instagram_content_summary",
    "content_quick_routine_demo",
    "mentions",
    0.78,
    0.75,
    "Instagram digest highlights quick routine demos as a save-friendly asset.",
  ),
  makeEdge(
    "edge_source_instagram_supports_clean",
    "source_instagram_content_summary",
    "selling_clean_ingredient_story",
    "supports",
    0.75,
    0.73,
    "Instagram content digest reinforces the clean ingredient angle.",
  ),
  makeEdge(
    "edge_source_insight_supports_hook",
    "source_insight_report_fragment",
    "content_emotional_problem_hook",
    "supports",
    0.8,
    0.79,
    "The insight report supports emotional hooks for younger audiences.",
  ),
  makeEdge(
    "edge_source_insight_supports_tiktok",
    "source_insight_report_fragment",
    "platform_tiktok",
    "supports",
    0.78,
    0.77,
    "The report calls out TikTok as the higher-velocity discovery platform.",
  ),
  makeEdge(
    "edge_source_insight_mentions_content_fatigue",
    "source_insight_report_fragment",
    "mechanism_content_fatigue",
    "mentions",
    0.69,
    0.74,
    "The report explicitly mentions fatigue from repetitive claim structures.",
  ),
  makeEdge(
    "edge_product_belongs_brand",
    "product_scalp_repair_serum",
    "brand_headease",
    "belongs_to",
    0.99,
    0.99,
    "Scalp Repair Serum belongs to HeadEase.",
  ),
  makeEdge(
    "edge_brand_belongs_category",
    "brand_headease",
    "category_scalp_care",
    "belongs_to",
    0.9,
    0.93,
    "HeadEase belongs to the scalp care category.",
  ),
  makeEdge(
    "edge_brand_compares_nutra",
    "brand_headease",
    "brand_nutraroot",
    "compares_with",
    0.72,
    0.79,
    "HeadEase is benchmarked against NutraRoot.",
  ),
  makeEdge(
    "edge_brand_compares_clear",
    "brand_headease",
    "brand_clearscalp_lab",
    "compares_with",
    0.74,
    0.79,
    "HeadEase is benchmarked against ClearScalp Lab.",
  ),
  makeEdge(
    "edge_before_after_tiktok",
    "content_before_after_story",
    "platform_tiktok",
    "fits_platform",
    0.88,
    0.88,
    "Before/after story fits TikTok's proof loop.",
  ),
  makeEdge(
    "edge_breakdown_instagram",
    "content_ingredient_breakdown",
    "platform_instagram",
    "fits_platform",
    0.87,
    0.89,
    "Ingredient breakdown fits Instagram's saveable explainer behavior.",
  ),
  makeEdge(
    "edge_demo_tiktok",
    "content_quick_routine_demo",
    "platform_tiktok",
    "fits_platform",
    0.73,
    0.76,
    "Quick routine demo fits TikTok's fast how-to loop.",
  ),
  makeEdge(
    "edge_demo_instagram",
    "content_quick_routine_demo",
    "platform_instagram",
    "fits_platform",
    0.77,
    0.8,
    "Quick routine demo also fits Instagram's routine-led save behavior.",
  ),
  makeEdge(
    "edge_emotional_targets_young",
    "content_emotional_problem_hook",
    "user_young_women_18_24",
    "targets",
    0.9,
    0.9,
    "Emotional problem hook targets younger women on discovery platforms.",
  ),
  makeEdge(
    "edge_expert_targets_ingredient",
    "content_expert_explanation",
    "user_ingredient_conscious_buyers",
    "targets",
    0.86,
    0.89,
    "Expert explanation targets ingredient-conscious buyers.",
  ),
  makeEdge(
    "edge_derm_emphasizes_trust",
    "selling_dermatologist_tested",
    "concern_trustworthiness",
    "emphasizes",
    0.91,
    0.92,
    "Dermatologist-tested emphasizes trustworthiness.",
  ),
  makeEdge(
    "edge_visible_emphasizes_proof",
    "selling_visible_scalp_comfort_7_days",
    "concern_proof_of_efficacy",
    "emphasizes",
    0.88,
    0.9,
    "7-day comfort claim emphasizes proof of efficacy.",
  ),
  makeEdge(
    "edge_clean_targets_ingredient",
    "selling_clean_ingredient_story",
    "user_ingredient_conscious_buyers",
    "targets",
    0.87,
    0.88,
    "Clean ingredient story targets ingredient-conscious buyers.",
  ),
  makeEdge(
    "edge_soothing_targets_sensitive",
    "selling_soothing_scalp_irritation",
    "user_sensitive_scalp_users",
    "targets",
    0.89,
    0.9,
    "Soothing irritation directly targets sensitive scalp users.",
  ),
  makeEdge(
    "edge_texture_targets_working",
    "selling_lightweight_non_greasy_texture",
    "user_working_women_25_34",
    "targets",
    0.78,
    0.84,
    "Lightweight texture targets routine-conscious working women.",
  ),
  makeEdge(
    "edge_itch_targets_sensitive",
    "concern_itch_relief",
    "user_sensitive_scalp_users",
    "targets",
    0.82,
    0.8,
    "Itch relief is a core target concern for sensitive scalp users.",
  ),
  makeEdge(
    "edge_price_targets_price_sensitive",
    "concern_price_value_balance",
    "user_price_sensitive_buyers",
    "targets",
    0.86,
    0.86,
    "Price-value balance targets price-sensitive buyers.",
  ),
  makeEdge(
    "edge_nutra_contains_halo",
    "brand_nutraroot",
    "competitor_nutraroot_herbal_halo",
    "contains",
    0.78,
    0.83,
    "NutraRoot contains a strong herbal-halo positioning cue.",
  ),
  makeEdge(
    "edge_clear_contains_clinical",
    "brand_clearscalp_lab",
    "competitor_clearscalp_clinical_aesthetic",
    "contains",
    0.8,
    0.84,
    "ClearScalp Lab contains a clinical aesthetic cue.",
  ),
  makeEdge(
    "edge_memory_history_brand",
    "historical_brand_positioning",
    "brand_headease",
    "belongs_to",
    0.74,
    0.77,
    "Historical brand positioning belongs to HeadEase.",
  ),
  makeEdge(
    "edge_brand_contains_soothing",
    "brand_headease",
    "selling_soothing_scalp_irritation",
    "contains",
    0.82,
    0.88,
    "HeadEase contains a soothing scalp irritation claim.",
  ),
  makeEdge(
    "edge_brand_contains_clean",
    "brand_headease",
    "selling_clean_ingredient_story",
    "contains",
    0.81,
    0.85,
    "HeadEase contains a clean ingredient story.",
  ),
  makeEdge(
    "edge_brand_contains_derm",
    "brand_headease",
    "selling_dermatologist_tested",
    "contains",
    0.84,
    0.88,
    "HeadEase contains dermatologist-tested proof language.",
  ),
  makeEdge(
    "edge_product_contains_texture",
    "product_scalp_repair_serum",
    "selling_lightweight_non_greasy_texture",
    "contains",
    0.87,
    0.92,
    "The serum contains a lightweight texture proof point.",
  ),
  makeEdge(
    "edge_product_contains_7days",
    "product_scalp_repair_serum",
    "selling_visible_scalp_comfort_7_days",
    "contains",
    0.89,
    0.92,
    "The serum contains the 7-day comfort promise.",
  ),
  makeEdge(
    "edge_emotional_increases_hook",
    "content_emotional_problem_hook",
    "mechanism_hook_strength",
    "increases",
    0.93,
    0.9,
    "Emotional problem hook increases hook strength.",
  ),
  makeEdge(
    "edge_visible_increases_clarity",
    "selling_visible_scalp_comfort_7_days",
    "mechanism_benefit_clarity",
    "increases",
    0.92,
    0.91,
    "Visible comfort in 7 days increases benefit clarity.",
  ),
  makeEdge(
    "edge_derm_increases_trust",
    "selling_dermatologist_tested",
    "mechanism_trust_formation",
    "increases",
    0.94,
    0.94,
    "Dermatologist-tested increases trust formation.",
  ),
  makeEdge(
    "edge_before_after_increases_social",
    "content_before_after_story",
    "mechanism_social_proof",
    "increases",
    0.88,
    0.86,
    "Before/after story increases social proof.",
  ),
  makeEdge(
    "edge_breakdown_increases_load",
    "content_ingredient_breakdown",
    "mechanism_cognitive_load",
    "increases",
    0.54,
    0.83,
    "Ingredient breakdown lightly increases cognitive load.",
  ),
  makeEdge(
    "edge_demo_increases_fit",
    "content_quick_routine_demo",
    "mechanism_native_platform_fit",
    "increases",
    0.86,
    0.87,
    "Quick routine demo increases native platform fit.",
  ),
  makeEdge(
    "edge_exaggerated_increases_skepticism",
    "risk_exaggerated_claims",
    "mechanism_skepticism_trigger",
    "increases",
    0.91,
    0.88,
    "Exaggerated claims increase skepticism.",
  ),
  makeEdge(
    "edge_many_claims_increases_load",
    "risk_too_many_claims",
    "mechanism_cognitive_load",
    "increases",
    0.87,
    0.87,
    "Too many claims increase cognitive load.",
  ),
  makeEdge(
    "edge_high_price_increases_friction",
    "risk_high_price_positioning",
    "mechanism_conversion_friction",
    "increases",
    0.89,
    0.88,
    "High price positioning increases conversion friction.",
  ),
  makeEdge(
    "edge_clean_increases_resonance",
    "selling_clean_ingredient_story",
    "mechanism_emotional_resonance",
    "increases",
    0.85,
    0.86,
    "Clean ingredient story increases emotional resonance.",
  ),
  makeEdge(
    "edge_expert_increases_trust",
    "content_expert_explanation",
    "mechanism_trust_formation",
    "increases",
    0.82,
    0.81,
    "Expert explanation increases trust formation.",
  ),
  makeEdge(
    "edge_soothing_increases_resonance",
    "selling_soothing_scalp_irritation",
    "mechanism_emotional_resonance",
    "increases",
    0.84,
    0.84,
    "Soothing irritation increases emotional resonance.",
  ),
  makeEdge(
    "edge_texture_reduces_friction",
    "selling_lightweight_non_greasy_texture",
    "mechanism_conversion_friction",
    "reduces",
    0.62,
    0.8,
    "Lightweight texture slightly reduces routine friction.",
  ),
  makeEdge(
    "edge_proof_triggers_trust",
    "concern_proof_of_efficacy",
    "mechanism_trust_formation",
    "triggers",
    0.63,
    0.78,
    "Proof demand triggers the need for trust formation.",
  ),
  makeEdge(
    "edge_fear_triggers_skepticism",
    "concern_fear_of_irritation",
    "mechanism_skepticism_trigger",
    "triggers",
    0.68,
    0.81,
    "Fear of irritation can trigger skepticism without safety evidence.",
  ),
  makeEdge(
    "edge_competitor_clear_conflicts_clean",
    "competitor_clearscalp_clinical_aesthetic",
    "selling_clean_ingredient_story",
    "conflicts_with",
    0.52,
    0.72,
    "The clinical competitor frame can conflict with softer clean storytelling.",
  ),
  makeEdge(
    "edge_competitor_nutra_conflicts_derm",
    "competitor_nutraroot_herbal_halo",
    "selling_dermatologist_tested",
    "conflicts_with",
    0.48,
    0.7,
    "A purely herbal competitor frame competes with the dermatologist proof axis.",
  ),
  makeEdge(
    "edge_hook_to_click",
    "mechanism_hook_strength",
    "outcome_click_intent",
    "increases",
    0.92,
    0.92,
    "Hook strength increases click intent.",
  ),
  makeEdge(
    "edge_clarity_to_retention",
    "mechanism_benefit_clarity",
    "outcome_watch_retention",
    "increases",
    0.87,
    0.89,
    "Benefit clarity increases watch retention.",
  ),
  makeEdge(
    "edge_trust_to_conversion",
    "mechanism_trust_formation",
    "outcome_conversion_interest",
    "increases",
    0.94,
    0.93,
    "Trust formation increases conversion interest.",
  ),
  makeEdge(
    "edge_social_to_comments",
    "mechanism_social_proof",
    "outcome_comment_engagement",
    "increases",
    0.84,
    0.87,
    "Social proof increases comment engagement.",
  ),
  makeEdge(
    "edge_fit_to_share",
    "mechanism_native_platform_fit",
    "outcome_share_potential",
    "increases",
    0.86,
    0.88,
    "Native platform fit increases share potential.",
  ),
  makeEdge(
    "edge_load_reduces_retention",
    "mechanism_cognitive_load",
    "outcome_watch_retention",
    "reduces",
    0.88,
    0.89,
    "Cognitive load reduces watch retention.",
  ),
  makeEdge(
    "edge_skepticism_reduces_sentiment",
    "mechanism_skepticism_trigger",
    "outcome_positive_sentiment",
    "reduces",
    0.89,
    0.9,
    "Skepticism reduces positive sentiment.",
  ),
  makeEdge(
    "edge_friction_reduces_conversion",
    "mechanism_conversion_friction",
    "outcome_conversion_interest",
    "reduces",
    0.9,
    0.9,
    "Conversion friction reduces conversion interest.",
  ),
  makeEdge(
    "edge_resonance_increases_sentiment",
    "mechanism_emotional_resonance",
    "outcome_positive_sentiment",
    "increases",
    0.85,
    0.87,
    "Emotional resonance increases positive sentiment.",
  ),
  makeEdge(
    "edge_skepticism_increases_risk",
    "mechanism_skepticism_trigger",
    "outcome_risk_exposure",
    "increases",
    0.91,
    0.9,
    "Skepticism increases risk exposure.",
  ),
  makeEdge(
    "edge_trust_leads_sentiment",
    "mechanism_trust_formation",
    "outcome_positive_sentiment",
    "leads_to",
    0.74,
    0.84,
    "Trust formation often leads to more positive sentiment.",
  ),
  makeEdge(
    "edge_resonance_to_share",
    "mechanism_emotional_resonance",
    "outcome_share_potential",
    "increases",
    0.69,
    0.8,
    "Emotional resonance supports sharing behavior.",
  ),
  makeEdge(
    "edge_content_fatigue_reduces_retention",
    "mechanism_content_fatigue",
    "outcome_watch_retention",
    "reduces",
    0.72,
    0.78,
    "Content fatigue reduces watch retention.",
  ),
  makeEdge(
    "edge_content_fatigue_reduces_comments",
    "mechanism_content_fatigue",
    "outcome_comment_engagement",
    "reduces",
    0.66,
    0.76,
    "Content fatigue reduces comment engagement.",
  ),
];

export const tailGroups: TailNodeGroup[] = [
  {
    prefix: "tail_signal",
    count: 12,
    layer: "source",
    filterType: "source",
    entityType: "tail_signal",
    anchors: [
      "source_insight_report_fragment",
      "source_instagram_content_summary",
      "source_memory_bank_brand_history",
    ],
    relationType: "contains",
    secondaryTargets: [
      "selling_clean_ingredient_story",
      "content_quick_routine_demo",
      "mechanism_content_fatigue",
      "platform_instagram",
    ],
    summaryPrefix:
      "Low-volume but recurring signal cluster reinforcing secondary platform or claim patterns.",
  },
  {
    prefix: "tail_comment_cluster",
    count: 12,
    layer: "source",
    filterType: "source",
    entityType: "tail_comment_cluster",
    anchors: [
      "source_tiktok_comment_summary",
      "source_instagram_content_summary",
      "source_user_interview_notes",
    ],
    relationType: "contains",
    secondaryTargets: [
      "concern_itch_relief",
      "concern_fear_of_irritation",
      "concern_trustworthiness",
      "concern_price_value_balance",
    ],
    summaryPrefix:
      "Long-tail comment cluster pointing to weaker but repeated audience anxieties.",
  },
  {
    prefix: "weak_interest_group",
    count: 12,
    layer: "fact",
    filterType: "user",
    entityType: "tail_audience_cluster",
    anchors: [
      "user_young_women_18_24",
      "user_working_women_25_34",
      "user_sensitive_scalp_users",
      "user_ingredient_conscious_buyers",
    ],
    relationType: "belongs_to",
    secondaryTargets: [
      "concern_oil_control",
      "selling_lightweight_non_greasy_texture",
      "selling_clean_ingredient_story",
      "content_quick_routine_demo",
    ],
    summaryPrefix:
      "Small audience slice connected to a narrower scalp-care intent or routine behavior.",
  },
  {
    prefix: "secondary_claim",
    count: 8,
    layer: "fact",
    filterType: "selling_point",
    entityType: "tail_claim",
    anchors: [
      "selling_soothing_scalp_irritation",
      "selling_visible_scalp_comfort_7_days",
      "selling_lightweight_non_greasy_texture",
      "selling_clean_ingredient_story",
    ],
    relationType: "supports",
    secondaryTargets: [
      "mechanism_benefit_clarity",
      "mechanism_emotional_resonance",
      "mechanism_cognitive_load",
      "risk_exaggerated_claims",
    ],
    summaryPrefix:
      "Secondary claim variant that adds density but is weaker than the hero messaging spine.",
  },
];
