export type CreatorGender = 'female' | 'male';

export interface CreatorLibraryItem {
  id: string;
  name: string;
  handle: string;
  followers: string;
  niche: string;
  region: string;
  avgViews: string;
  avatarUrl: string;
  gender: CreatorGender;
  genderSymbol: '♀' | '♂';
}

export const creatorLibraryItems: CreatorLibraryItem[] = [
  {
    id: 'creator-01',
    name: 'Camila Reed',
    handle: '@camilareviewslab',
    followers: '182.4K',
    niche: '护肤测评',
    region: 'US',
    avgViews: '28.6万',
    avatarUrl: '/model-avatars/C.jpg',
    gender: 'female',
    genderSymbol: '♀',
  },
  {
    id: 'creator-02',
    name: 'Nora Hayes',
    handle: '@nora.finds',
    followers: '96.8K',
    niche: '美妆种草',
    region: 'US',
    avgViews: '14.2万',
    avatarUrl: '/model-avatars/g31fip2k-1776075998608-89d9b78b.jpg',
    gender: 'female',
    genderSymbol: '♀',
  },
  {
    id: 'creator-03',
    name: 'Ari Monroe',
    handle: '@ariugcstudio',
    followers: '254.1K',
    niche: 'UGC 带货',
    region: 'UK',
    avgViews: '33.8万',
    avatarUrl: '/model-avatars/g31fip2k-1776076035765-d58d45d2.jpg',
    gender: 'male',
    genderSymbol: '♂',
  },
  {
    id: 'creator-04',
    name: 'Jade Collins',
    handle: '@jadebeautydiary',
    followers: '128.7K',
    niche: '眼部护理',
    region: 'CA',
    avgViews: '18.5万',
    avatarUrl: '/model-avatars/image-model-001.jpg',
    gender: 'female',
    genderSymbol: '♀',
  },
  {
    id: 'creator-05',
    name: 'Sienna Brooks',
    handle: '@siennaskinclub',
    followers: '341.9K',
    niche: '熟龄护肤',
    region: 'US',
    avgViews: '41.3万',
    avatarUrl: '/model-avatars/image-model-003.jpg',
    gender: 'female',
    genderSymbol: '♀',
  },
  {
    id: 'creator-06',
    name: 'Mila Carter',
    handle: '@mila.shopnotes',
    followers: '77.2K',
    niche: 'TikTok Shop',
    region: 'AU',
    avgViews: '9.7万',
    avatarUrl: '/model-avatars/image-model-005.jpg',
    gender: 'female',
    genderSymbol: '♀',
  },
  {
    id: 'creator-07',
    name: 'Ava Bennett',
    handle: '@ava.glowedit',
    followers: '205.6K',
    niche: '美妆教程',
    region: 'US',
    avgViews: '25.4万',
    avatarUrl: '/model-avatars/image-model-006.jpg',
    gender: 'female',
    genderSymbol: '♀',
  },
  {
    id: 'creator-08',
    name: 'Chloe Hart',
    handle: '@chloetrendbook',
    followers: '149.5K',
    niche: '爆款拆解',
    region: 'SG',
    avgViews: '16.8万',
    avatarUrl: '/model-avatars/image-model-007.jpg',
    gender: 'male',
    genderSymbol: '♂',
  },
  {
    id: 'creator-09',
    name: 'Luna Carter',
    handle: '@luna.skinnotes',
    followers: '116.3K',
    niche: '功效护肤',
    region: 'US',
    avgViews: '12.7万',
    avatarUrl: '/model-avatars/image-model-001 (1).jpg',
    gender: 'female',
    genderSymbol: '♀',
  },
  {
    id: 'creator-10',
    name: 'Miles Avery',
    handle: '@miles.productlab',
    followers: '88.9K',
    niche: '产品评测',
    region: 'UK',
    avgViews: '10.6万',
    avatarUrl: '/model-avatars/image-model-002 (2).jpg',
    gender: 'male',
    genderSymbol: '♂',
  },
  {
    id: 'creator-11',
    name: 'Ella Morgan',
    handle: '@ella.glowclub',
    followers: '194.2K',
    niche: '达人种草',
    region: 'CA',
    avgViews: '20.3万',
    avatarUrl: '/model-avatars/image-model-008 (1).jpg',
    gender: 'female',
    genderSymbol: '♀',
  },
  {
    id: 'creator-12',
    name: 'Noah Sterling',
    handle: '@noah.trendwatch',
    followers: '132.8K',
    niche: '趋势拆解',
    region: 'US',
    avgViews: '15.1万',
    avatarUrl: '/model-avatars/image-model-009 (1).jpg',
    gender: 'male',
    genderSymbol: '♂',
  },
];
