export type CreatorGender = 'female' | 'male';

export type CreatorSegment =
  | 'cn-male'
  | 'cn-female'
  | 'overseas-white-male'
  | 'overseas-white-female'
  | 'overseas-black-male'
  | 'overseas-black-female';

export interface CreatorLibraryItem {
  id: string;
  name: string;
  handle: string;
  followers: string;
  niche: string;
  region: string;
  avgViews: string;
  avatarUrl: string;
  gender: CreatorGender;
  genderSymbol: '♀' | '♂';
  segment: CreatorSegment;
}

type CreatorSeed = Omit<CreatorLibraryItem, 'id' | 'genderSymbol'>;

const creatorSeeds: CreatorSeed[] = [
  {
    name: 'Camila Reed',
    handle: '@camilareviewslab',
    followers: '182.4K',
    niche: '护肤测评',
    region: 'CN',
    avgViews: '28.6万',
    avatarUrl: '/model-avatars/cn-male/creator-01.jpg',
    gender: 'male',
    segment: 'cn-male',
  },
  {
    name: 'Nora Hayes',
    handle: '@nora.finds',
    followers: '96.8K',
    niche: '美妆种草',
    region: 'CN',
    avgViews: '14.2万',
    avatarUrl: '/model-avatars/cn-male/creator-02.jpg',
    gender: 'male',
    segment: 'cn-male',
  },
  {
    name: 'Ari Monroe',
    handle: '@ariugcstudio',
    followers: '254.1K',
    niche: 'UGC 带货',
    region: 'CN',
    avgViews: '33.8万',
    avatarUrl: '/model-avatars/cn-male/creator-03.jpg',
    gender: 'male',
    segment: 'cn-male',
  },
  {
    name: 'Jade Collins',
    handle: '@jadebeautydiary',
    followers: '128.7K',
    niche: '眼部护理',
    region: 'CN',
    avgViews: '18.5万',
    avatarUrl: '/model-avatars/cn-male/creator-04.jpg',
    gender: 'male',
    segment: 'cn-male',
  },
  {
    name: 'Sienna Brooks',
    handle: '@siennaskinclub',
    followers: '341.9K',
    niche: '熟龄护肤',
    region: 'CN',
    avgViews: '41.3万',
    avatarUrl: '/model-avatars/cn-male/creator-05.jpg',
    gender: 'male',
    segment: 'cn-male',
  },
  {
    name: 'Mila Carter',
    handle: '@mila.shopnotes',
    followers: '77.2K',
    niche: 'TikTok Shop',
    region: 'CN',
    avgViews: '9.7万',
    avatarUrl: '/model-avatars/cn-male/creator-06.jpg',
    gender: 'male',
    segment: 'cn-male',
  },
  {
    name: 'Ava Bennett',
    handle: '@ava.glowedit',
    followers: '205.6K',
    niche: '美妆教程',
    region: 'CN',
    avgViews: '25.4万',
    avatarUrl: '/model-avatars/cn-male/creator-07.jpg',
    gender: 'male',
    segment: 'cn-male',
  },
  {
    name: 'Chloe Hart',
    handle: '@chloetrendbook',
    followers: '149.5K',
    niche: '爆款拆解',
    region: 'CN',
    avgViews: '16.8万',
    avatarUrl: '/model-avatars/cn-male/creator-08.jpg',
    gender: 'male',
    segment: 'cn-male',
  },
  {
    name: 'Luna Carter',
    handle: '@luna.skinnotes',
    followers: '116.3K',
    niche: '功效护肤',
    region: 'CN',
    avgViews: '12.7万',
    avatarUrl: '/model-avatars/cn-male/creator-09.jpg',
    gender: 'male',
    segment: 'cn-male',
  },
  {
    name: 'Miles Avery',
    handle: '@miles.productlab',
    followers: '88.9K',
    niche: '产品测评',
    region: 'CN',
    avgViews: '10.6万',
    avatarUrl: '/model-avatars/cn-male/creator-10.jpg',
    gender: 'male',
    segment: 'cn-male',
  },
  {
    name: 'Ella Morgan',
    handle: '@ella.glowclub',
    followers: '194.2K',
    niche: '达人种草',
    region: 'CN',
    avgViews: '20.3万',
    avatarUrl: '/model-avatars/cn-male/creator-11.jpg',
    gender: 'male',
    segment: 'cn-male',
  },
  {
    name: 'Noah Sterling',
    handle: '@noah.trendwatch',
    followers: '132.8K',
    niche: '趋势拆解',
    region: 'CN',
    avgViews: '15.1万',
    avatarUrl: '/model-avatars/cn-male/creator-12.jpg',
    gender: 'male',
    segment: 'cn-male',
  },
  {
    name: 'Ruoxi Lin',
    handle: '@ruoxi.skindiary',
    followers: '118.6K',
    niche: '护肤测评',
    region: 'CN',
    avgViews: '12.4万',
    avatarUrl: '/model-avatars/cn-female/creator-01.jpg',
    gender: 'female',
    segment: 'cn-female',
  },
  {
    name: 'Wanqing Su',
    handle: '@wanqing.beautylog',
    followers: '156.2K',
    niche: '美妆种草',
    region: 'CN',
    avgViews: '18.9万',
    avatarUrl: '/model-avatars/cn-female/creator-02.jpg',
    gender: 'female',
    segment: 'cn-female',
  },
  {
    name: 'Xingyao Gu',
    handle: '@xingyao.glowclub',
    followers: '203.5K',
    niche: '成分护肤',
    region: 'CN',
    avgViews: '24.7万',
    avatarUrl: '/model-avatars/cn-female/creator-03.jpg',
    gender: 'female',
    segment: 'cn-female',
  },
  {
    name: 'Zhixia Xu',
    handle: '@zhixia.skinnotes',
    followers: '94.3K',
    niche: '功效护肤',
    region: 'CN',
    avgViews: '10.8万',
    avatarUrl: '/model-avatars/cn-female/creator-04.jpg',
    gender: 'female',
    segment: 'cn-female',
  },
  {
    name: 'Kelan Wen',
    handle: '@kelan.beautydiary',
    followers: '176.8K',
    niche: '彩妆教程',
    region: 'CN',
    avgViews: '19.6万',
    avatarUrl: '/model-avatars/cn-female/creator-05.jpg',
    gender: 'female',
    segment: 'cn-female',
  },
  {
    name: 'Yuan Shen',
    handle: '@yuan.makeuplab',
    followers: '132.4K',
    niche: '妆容拆解',
    region: 'CN',
    avgViews: '14.9万',
    avatarUrl: '/model-avatars/cn-female/creator-06.jpg',
    gender: 'female',
    segment: 'cn-female',
  },
  {
    name: 'Tingyu Qiao',
    handle: '@tingyu.skincare',
    followers: '216.7K',
    niche: '熟龄护肤',
    region: 'CN',
    avgViews: '26.3万',
    avatarUrl: '/model-avatars/cn-female/creator-07.jpg',
    gender: 'female',
    segment: 'cn-female',
  },
  {
    name: 'Zhiwei Song',
    handle: '@zhiwei.trendlab',
    followers: '145.1K',
    niche: '爆款拆解',
    region: 'CN',
    avgViews: '16.5万',
    avatarUrl: '/model-avatars/cn-female/creator-08.jpg',
    gender: 'female',
    segment: 'cn-female',
  },
  {
    name: 'Qingtang Lu',
    handle: '@qingtang.dailylook',
    followers: '168.9K',
    niche: '达人种草',
    region: 'CN',
    avgViews: '20.2万',
    avatarUrl: '/model-avatars/cn-female/creator-09.jpg',
    gender: 'female',
    segment: 'cn-female',
  },
  {
    name: 'Nianchu Bai',
    handle: '@nianchu.glowshop',
    followers: '87.5K',
    niche: 'TikTok Shop',
    region: 'CN',
    avgViews: '9.3万',
    avatarUrl: '/model-avatars/cn-female/creator-10.jpg',
    gender: 'female',
    segment: 'cn-female',
  },
  {
    name: 'Shiyi Jiang',
    handle: '@shiyi.productreview',
    followers: '121.7K',
    niche: '产品测评',
    region: 'CN',
    avgViews: '13.6万',
    avatarUrl: '/model-avatars/cn-female/creator-11.jpg',
    gender: 'female',
    segment: 'cn-female',
  },
  {
    name: 'Yuning Tang',
    handle: '@yuning.trendwatch',
    followers: '189.8K',
    niche: '趋势拆解',
    region: 'CN',
    avgViews: '21.7万',
    avatarUrl: '/model-avatars/cn-female/creator-12.jpg',
    gender: 'female',
    segment: 'cn-female',
  },
  {
    name: 'Anran Li',
    handle: '@anran.skinstudio',
    followers: '109.2K',
    niche: '眼部护理',
    region: 'CN',
    avgViews: '11.5万',
    avatarUrl: '/model-avatars/cn-female/creator-13.jpg',
    gender: 'female',
    segment: 'cn-female',
  },
  {
    name: 'Yimo Zhou',
    handle: '@yimo.beautyedit',
    followers: '174.6K',
    niche: '美妆教程',
    region: 'CN',
    avgViews: '19.8万',
    avatarUrl: '/model-avatars/cn-female/creator-14.jpg',
    gender: 'female',
    segment: 'cn-female',
  },
  {
    name: 'Ethan Carter',
    handle: '@ethan.reviewlab',
    followers: '164.8K',
    niche: '产品测评',
    region: 'US',
    avgViews: '18.4万',
    avatarUrl: '/model-avatars/overseas-male/creator-01.jpg',
    gender: 'male',
    segment: 'overseas-white-male',
  },
  {
    name: 'Lucas Brooks',
    handle: '@lucas.shopnotes',
    followers: '97.6K',
    niche: 'TikTok Shop',
    region: 'US',
    avgViews: '10.9万',
    avatarUrl: '/model-avatars/overseas-male/creator-02.jpg',
    gender: 'male',
    segment: 'overseas-white-male',
  },
  {
    name: 'Noah Walker',
    handle: '@noah.trendwatch',
    followers: '143.2K',
    niche: '趋势拆解',
    region: 'UK',
    avgViews: '15.7万',
    avatarUrl: '/model-avatars/overseas-male/creator-03.jpg',
    gender: 'male',
    segment: 'overseas-white-male',
  },
  {
    name: 'Liam Scott',
    handle: '@liam.menstyle',
    followers: '186.5K',
    niche: '爆款拆解',
    region: 'CA',
    avgViews: '20.5万',
    avatarUrl: '/model-avatars/overseas-male/creator-04.jpg',
    gender: 'male',
    segment: 'overseas-white-male',
  },
  {
    name: 'Mason Reed',
    handle: '@mason.skinnotes',
    followers: '112.7K',
    niche: '护肤测评',
    region: 'AU',
    avgViews: '12.8万',
    avatarUrl: '/model-avatars/overseas-male/creator-05.jpg',
    gender: 'male',
    segment: 'overseas-white-male',
  },
  {
    name: 'Aiden Cooper',
    handle: '@aiden.groomlab',
    followers: '154.9K',
    niche: '男士护理',
    region: 'US',
    avgViews: '17.6万',
    avatarUrl: '/model-avatars/overseas-male/creator-06.jpg',
    gender: 'male',
    segment: 'overseas-white-male',
  },
  {
    name: 'Elijah Ross',
    handle: '@elijah.productlab',
    followers: '128.4K',
    niche: '产品测评',
    region: 'UK',
    avgViews: '14.1万',
    avatarUrl: '/model-avatars/overseas-male/creator-07.jpg',
    gender: 'male',
    segment: 'overseas-white-male',
  },
  {
    name: 'Julian Hayes',
    handle: '@julian.glowedit',
    followers: '173.6K',
    niche: '美妆教程',
    region: 'CA',
    avgViews: '19.3万',
    avatarUrl: '/model-avatars/overseas-male/creator-08.jpg',
    gender: 'male',
    segment: 'overseas-white-male',
  },
  {
    name: 'Caleb Morgan',
    handle: '@caleb.ugcstudio',
    followers: '201.8K',
    niche: 'UGC 带货',
    region: 'US',
    avgViews: '23.9万',
    avatarUrl: '/model-avatars/overseas-male/creator-09.jpg',
    gender: 'male',
    segment: 'overseas-white-male',
  },
  {
    name: 'Owen Turner',
    handle: '@owen.dailyfinds',
    followers: '89.7K',
    niche: '达人种草',
    region: 'SG',
    avgViews: '9.8万',
    avatarUrl: '/model-avatars/overseas-male/creator-10.jpg',
    gender: 'male',
    segment: 'overseas-white-male',
  },
  {
    name: 'Levi Bennett',
    handle: '@levi.skinreview',
    followers: '137.1K',
    niche: '功效护肤',
    region: 'AU',
    avgViews: '15.2万',
    avatarUrl: '/model-avatars/overseas-male/creator-11.jpg',
    gender: 'male',
    segment: 'overseas-white-male',
  },
  {
    name: 'Ryan Cole',
    handle: '@ryan.trendbook',
    followers: '167.3K',
    niche: '趋势拆解',
    region: 'US',
    avgViews: '18.8万',
    avatarUrl: '/model-avatars/overseas-male/creator-12.jpg',
    gender: 'male',
    segment: 'overseas-white-male',
  },
  {
    name: 'Avery Wilson',
    handle: '@avery.glownotes',
    followers: '146.2K',
    niche: '美妆种草',
    region: 'US',
    avgViews: '16.1万',
    avatarUrl: '/model-avatars/overseas-female/white-female-01.jpg',
    gender: 'female',
    segment: 'overseas-white-female',
  },
  {
    name: 'Claire Foster',
    handle: '@claire.skinjournal',
    followers: '118.4K',
    niche: '护肤测评',
    region: 'UK',
    avgViews: '13.4万',
    avatarUrl: '/model-avatars/overseas-female/white-female-02.jpg',
    gender: 'female',
    segment: 'overseas-white-female',
  },
  {
    name: 'Emilia Brooks',
    handle: '@emilia.beautyedit',
    followers: '172.7K',
    niche: '美妆教程',
    region: 'CA',
    avgViews: '19.2万',
    avatarUrl: '/model-avatars/overseas-female/white-female-03.jpg',
    gender: 'female',
    segment: 'overseas-white-female',
  },
  {
    name: 'Stella Hayes',
    handle: '@stella.trendclub',
    followers: '137.9K',
    niche: '趋势拆解',
    region: 'AU',
    avgViews: '15.6万',
    avatarUrl: '/model-avatars/overseas-female/white-female-04.jpg',
    gender: 'female',
    segment: 'overseas-white-female',
  },
  {
    name: 'Mia Parker',
    handle: '@mia.shopnotes',
    followers: '93.5K',
    niche: 'TikTok Shop',
    region: 'US',
    avgViews: '10.2万',
    avatarUrl: '/model-avatars/overseas-female/white-female-05.jpg',
    gender: 'female',
    segment: 'overseas-white-female',
  },
  {
    name: 'Ruby Bennett',
    handle: '@ruby.skinreview',
    followers: '161.4K',
    niche: '功效护肤',
    region: 'UK',
    avgViews: '18.7万',
    avatarUrl: '/model-avatars/overseas-female/white-female-06.jpg',
    gender: 'female',
    segment: 'overseas-white-female',
  },
  {
    name: 'Natalie Woods',
    handle: '@natalie.glowlab',
    followers: '208.3K',
    niche: '达人种草',
    region: 'CA',
    avgViews: '24.1万',
    avatarUrl: '/model-avatars/overseas-female/white-female-07.jpg',
    gender: 'female',
    segment: 'overseas-white-female',
  },
  {
    name: 'Chloe Simmons',
    handle: '@chloe.makeupbook',
    followers: '124.8K',
    niche: '彩妆教程',
    region: 'AU',
    avgViews: '14.6万',
    avatarUrl: '/model-avatars/overseas-female/white-female-08.jpg',
    gender: 'female',
    segment: 'overseas-white-female',
  },
  {
    name: 'Grace Palmer',
    handle: '@grace.dailyfinds',
    followers: '149.1K',
    niche: '达人种草',
    region: 'US',
    avgViews: '16.8万',
    avatarUrl: '/model-avatars/overseas-female/white-female-09.jpg',
    gender: 'female',
    segment: 'overseas-white-female',
  },
  {
    name: 'Sophie Turner',
    handle: '@sophie.skindiary',
    followers: '132.6K',
    niche: '成分护肤',
    region: 'UK',
    avgViews: '15.1万',
    avatarUrl: '/model-avatars/overseas-female/white-female-10.jpg',
    gender: 'female',
    segment: 'overseas-white-female',
  },
  {
    name: 'Marcus Bryant',
    handle: '@marcus.reviewroom',
    followers: '158.7K',
    niche: '产品测评',
    region: 'US',
    avgViews: '17.3万',
    avatarUrl: '/model-avatars/overseas-male/black-male-01.jpg',
    gender: 'male',
    segment: 'overseas-black-male',
  },
  {
    name: 'Andre Coleman',
    handle: '@andre.trendwatch',
    followers: '142.5K',
    niche: '趋势拆解',
    region: 'UK',
    avgViews: '15.8万',
    avatarUrl: '/model-avatars/overseas-male/black-male-02.jpg',
    gender: 'male',
    segment: 'overseas-black-male',
  },
  {
    name: 'Devin Harris',
    handle: '@devin.shopnotes',
    followers: '101.9K',
    niche: 'TikTok Shop',
    region: 'CA',
    avgViews: '11.2万',
    avatarUrl: '/model-avatars/overseas-male/black-male-03.jpg',
    gender: 'male',
    segment: 'overseas-black-male',
  },
  {
    name: 'Jordan Mitchell',
    handle: '@jordan.groomlab',
    followers: '176.4K',
    niche: '男士护理',
    region: 'US',
    avgViews: '19.7万',
    avatarUrl: '/model-avatars/overseas-male/black-male-04.jpg',
    gender: 'male',
    segment: 'overseas-black-male',
  },
  {
    name: 'Xavier Brooks',
    handle: '@xavier.skinnotes',
    followers: '119.6K',
    niche: '护肤测评',
    region: 'AU',
    avgViews: '13.1万',
    avatarUrl: '/model-avatars/overseas-male/black-male-05.jpg',
    gender: 'male',
    segment: 'overseas-black-male',
  },
  {
    name: 'Isaiah Turner',
    handle: '@isaiah.ugcstudio',
    followers: '193.8K',
    niche: 'UGC 带货',
    region: 'US',
    avgViews: '22.6万',
    avatarUrl: '/model-avatars/overseas-male/black-male-06.jpg',
    gender: 'male',
    segment: 'overseas-black-male',
  },
  {
    name: 'Malik Foster',
    handle: '@malik.productlab',
    followers: '148.2K',
    niche: '产品测评',
    region: 'UK',
    avgViews: '16.2万',
    avatarUrl: '/model-avatars/overseas-male/black-male-07.jpg',
    gender: 'male',
    segment: 'overseas-black-male',
  },
  {
    name: 'Darius Bennett',
    handle: '@darius.dailyfinds',
    followers: '126.7K',
    niche: '达人种草',
    region: 'CA',
    avgViews: '14.4万',
    avatarUrl: '/model-avatars/overseas-male/black-male-08.jpg',
    gender: 'male',
    segment: 'overseas-black-male',
  },
  {
    name: 'Jamal Hayes',
    handle: '@jamal.glowedit',
    followers: '169.5K',
    niche: '美妆教程',
    region: 'US',
    avgViews: '18.9万',
    avatarUrl: '/model-avatars/overseas-male/black-male-09.jpg',
    gender: 'male',
    segment: 'overseas-black-male',
  },
  {
    name: 'Kieran Walker',
    handle: '@kieran.trendbook',
    followers: '134.1K',
    niche: '爆款拆解',
    region: 'AU',
    avgViews: '15.0万',
    avatarUrl: '/model-avatars/overseas-male/black-male-10.jpg',
    gender: 'male',
    segment: 'overseas-black-male',
  },
  {
    name: 'Tyson Reed',
    handle: '@tyson.skinreview',
    followers: '152.3K',
    niche: '功效护肤',
    region: 'US',
    avgViews: '17.1万',
    avatarUrl: '/model-avatars/overseas-male/black-male-11.jpg',
    gender: 'male',
    segment: 'overseas-black-male',
  },
  {
    name: 'Naomi Carter',
    handle: '@naomi.glowlab',
    followers: '163.8K',
    niche: '美妆种草',
    region: 'US',
    avgViews: '18.3万',
    avatarUrl: '/model-avatars/overseas-female/black-female-01.jpg',
    gender: 'female',
    segment: 'overseas-black-female',
  },
  {
    name: 'Aaliyah Brooks',
    handle: '@aaliyah.skinnotes',
    followers: '127.4K',
    niche: '护肤测评',
    region: 'UK',
    avgViews: '14.2万',
    avatarUrl: '/model-avatars/overseas-female/black-female-02.jpg',
    gender: 'female',
    segment: 'overseas-black-female',
  },
  {
    name: 'Zariah Mitchell',
    handle: '@zariah.trendclub',
    followers: '149.6K',
    niche: '趋势拆解',
    region: 'CA',
    avgViews: '16.7万',
    avatarUrl: '/model-avatars/overseas-female/black-female-03.jpg',
    gender: 'female',
    segment: 'overseas-black-female',
  },
  {
    name: 'Imani Foster',
    handle: '@imani.beautyedit',
    followers: '181.2K',
    niche: '美妆教程',
    region: 'US',
    avgViews: '20.1万',
    avatarUrl: '/model-avatars/overseas-female/black-female-04.jpg',
    gender: 'female',
    segment: 'overseas-black-female',
  },
  {
    name: 'Brielle Hayes',
    handle: '@brielle.shopnotes',
    followers: '98.5K',
    niche: 'TikTok Shop',
    region: 'AU',
    avgViews: '10.8万',
    avatarUrl: '/model-avatars/overseas-female/black-female-05.jpg',
    gender: 'female',
    segment: 'overseas-black-female',
  },
  {
    name: 'Jasmine Reed',
    handle: '@jasmine.glowedit',
    followers: '172.6K',
    niche: '达人种草',
    region: 'US',
    avgViews: '19.6万',
    avatarUrl: '/model-avatars/overseas-female/black-female-06.jpg',
    gender: 'female',
    segment: 'overseas-black-female',
  },
  {
    name: 'Maya Bennett',
    handle: '@maya.skinjournal',
    followers: '136.1K',
    niche: '功效护肤',
    region: 'UK',
    avgViews: '15.0万',
    avatarUrl: '/model-avatars/overseas-female/black-female-07.jpg',
    gender: 'female',
    segment: 'overseas-black-female',
  },
  {
    name: 'Kiara Palmer',
    handle: '@kiara.makeupbook',
    followers: '154.3K',
    niche: '彩妆教程',
    region: 'CA',
    avgViews: '17.4万',
    avatarUrl: '/model-avatars/overseas-female/black-female-08.jpg',
    gender: 'female',
    segment: 'overseas-black-female',
  },
  {
    name: 'Talia Woods',
    handle: '@talia.dailyfinds',
    followers: '121.8K',
    niche: '达人种草',
    region: 'US',
    avgViews: '13.9万',
    avatarUrl: '/model-avatars/overseas-female/black-female-09.jpg',
    gender: 'female',
    segment: 'overseas-black-female',
  },
  {
    name: 'Destiny Cole',
    handle: '@destiny.productlab',
    followers: '146.9K',
    niche: '产品测评',
    region: 'AU',
    avgViews: '16.5万',
    avatarUrl: '/model-avatars/overseas-female/black-female-10.jpg',
    gender: 'female',
    segment: 'overseas-black-female',
  },
  {
    name: 'Nylah Turner',
    handle: '@nylah.skindiary',
    followers: '133.7K',
    niche: '成分护肤',
    region: 'UK',
    avgViews: '14.8万',
    avatarUrl: '/model-avatars/overseas-female/black-female-11.jpg',
    gender: 'female',
    segment: 'overseas-black-female',
  },
  {
    name: 'Amara Simmons',
    handle: '@amara.trendwatch',
    followers: '175.4K',
    niche: '趋势拆解',
    region: 'US',
    avgViews: '19.9万',
    avatarUrl: '/model-avatars/overseas-female/black-female-12.jpg',
    gender: 'female',
    segment: 'overseas-black-female',
  },
];

export const creatorLibraryItems: CreatorLibraryItem[] = creatorSeeds.map((seed, index) => ({
  ...seed,
  id: `creator-${String(index + 1).padStart(2, '0')}`,
  genderSymbol: seed.gender === 'female' ? '♀' : '♂',
}));
